inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/spolitan/Analyses/ITS_Cluster_Studies/macros/outFileMCid_thr20final.root,
                ]
    objectnames: [hPDGcode] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: hPDGcode_MCOct # with path and w/o extension
    extensions: [pdf, root] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1, 1., 1, 1., 1., 1., 1., 1.]
    rebin: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    normalize: [true, true, true, true, true, true, true, true, true, true, false, false, false, false] # divide histogram by its area
    normRange: [3, 99]
    colors: [kRed+1, #kOrange+1, 
    kBlack]
    markers: [kOpenSquare, kOpenCircle, kFullSquare, kFullTriangleUp]
    markersize: 1.
    linewidth: 2
    linestyles: [1,8,3,4,5,6,7,1,1,1]
    fillstyle: [0,0,0,0,0,0,0,0,0,0]
    fillalpha: [1,1,1,1,1,1,1,1,1,1]
    drawopt: [hist, e, hist, hist, e, e, e, e, e]
    
    ratio: 
        enable: false
        uncertainties:
            enable: false
            corr: false
        displayRMS: false

    errcomp: # comparison of uncertainties
        enable: false
        relative: true
    
    KS: true
    dottedLine: ''

    legend:
        avoid: true #set true to avoid the legend in the final plot
        xlimits: [0.4, 0.7]
        ylimits: [0.7, 0.9]
        header: ''
        titles: ['a']
        options: [l, l, l, l, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 1

    canvas:
        width: 800
        heigth: 800
        xaxistitle: 'PDG code'
        yaxistitle: 'Counts'
        yaxistitleratio: ''
        xlimits: [0.00000000001, 100000]
        ylimits: [1.e-8, 1.e+4]
        ylimitsratio: [0, 3]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
