inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/spolitan/Analyses/ITS_Cluster_Studies/py/MCOriginStudy0208_EkinFix.root,
                /home/spolitan/Analyses/ITS_Cluster_Studies/py/MCOriginStudy0208_EkinFix.root
                ]
    objectnames: [hEtotal,
                  hEkin,
                  ] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: MCoriginEtotVsEkin_drays # with path and w/o extension
    extensions: [png] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1, 1., 1, 1., 1., 1., 1., 1.]
    rebin: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    normalize: [false, false, false, false, true, true, true, true, true, true, false, false, false, false] # divide histogram by its area
    normRange: [3, 99]
    colors: [ kRed, kAzure+4, 
    ]
    markers: [kOpenSquare, kOpenCircle, kFullTriangleUp, kFullTriangleUp]
    markersize: 1.
    linewidth: 2
    linestyles: [1,1,1,1]
    fillstyle: [0,0,0,0,0,0,0,0,0,0]
    fillalpha: [1,1,1,1,1,1,1,1,1,1]
    drawopt: [hist, hist, hist, hist, e, e, e, e, e]
    
    ratio: 
        enable: false
        uncertainties:
            enable: false
            corr: false
        displayRMS: false

    errcomp: # comparison of uncertainties
        enable: false
        relative: true
    
    KS: false
    dottedLine: ''

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.7, 0.8]
        ylimits: [0.7, 0.9]
        header: 'd-rays'
        titles: ['E_{tot}',
                 'E_{kin}'
                ]
        options: [l, l, l, l, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 1

    canvas:
        width: 800
        heigth: 800
        xaxistitle: 'MeV'
        yaxistitle: 'Counts'
        yaxistitleratio: ''
        xlimits: [0., 1.]
        ylimits: [1., 1.e+5]
        ylimitsratio: [0, 1.1]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
