inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/spolitan/Analyses/ITS_Cluster_Studies/JUNE/517689/raw/0840/outFileClSizeJuneNewMaskData.root,
                /home/spolitan/Analyses/ITS_Cluster_Studies/py/MCOriginStudyFracDraysNewCut_globalMC_281122.root,
                #/home/spolitan/Analyses/ITS_Cluster_Studies/py/MCOriginStudyOldMC_check.root,
                
                ]
    objectnames: [
                  #hCLsize,
                  hClSizehOct,
                  CLsize/hCLsize,
                  ] # can be either histograms of graphs or a mix of them; they will be drawn in the current order
# All: hCLsize,  hClSizehOct 
output: 
    filename: CompClSizeAll_MCFullProdwDraysCut_MCNewLocalProdwoDrayCut_DataOct # with path and w/o extension
    extensions: [png] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1, 1., 1, 1., 1., 1., 1., 1.]
    rebin: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    normalize: [true, true, true, true, true, true, true, true, true, true, false, false, false, false] # divide histogram by its area
    normrange: [3, 99]
    colors: [ kAzure+4,
              kRed+1,
            kBlack]
    markers: [kOpenSquare, kOpenCircle, kFullSquare, kFullTriangleUp]
    markersize: 1.
    linewidth: 2
    linestyles: [1,1,8,8]
    fillstyle: [1,1,1,0,0,0,0,0,0]
    fillalpha: [0.2,0.2,0.2,0.2,1,1,1,1,1,1]
    drawopt: [histe, histe, hist, hist, e, e, e, e, e]
    
    ratio: 
        enable: true
        uncertainties:
            enable: false
            corr: false
        displayRMS: false

    errcomp: # comparison of uncertainties
        enable: false
        relative: false
    
    KS: false
    dottedLine: ''

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.3, 0.6]
        ylimits: [0.7, 0.9]
        header: 'Data-to-MC'
        titles: [ #'MC Local prod. - w/o #delta-rays sel.',
                  PB Oct. 2021 (505658),
                 'MC Full prod. - w/o #delta-rays sel.',
        ]
        options: [fl, fl, fl, l, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 1

    canvas:
        width: 1600
        heigth: 800
        xaxistitle: 'Cluster size'
        yaxistitle: 'Norm. counts'
        yaxistitleratio: ''
        xlimits: [0, 99]
        ylimits: [1.e-8, 10]
        ylimitsratio: [1.e-3, 1.e+2]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: true
            logx: false
        errcomp:
            logy: false
            logx: false  
