inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/spolitan/Analyses/ITS_Cluster_Studies/py/MCOriginStudyFracDraysNewCut_globalMC_281122.root,
                /home/spolitan/Analyses/ITS_Cluster_Studies/py/MCOriginStudyglobalMC_wcut_1207.root,
                ]
    objectnames: [CLsize/hCLsize,
                  CLsize/hCLsize,
                  #hESel_procPrimary,
                  #hESel_procHInhelastic
                  ] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: MCdrays_clSize_w_wo_cut # with path and w/o extension 
    extensions: [png] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1, 1., 1, 1., 1., 1., 1., 1.]
    rebin: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    normalize: [true, true, false, false, false, true, true, true, true, true, false, false, false, false] # divide histogram by its area
    normrange: [1, 99]
    colors: [kRed+1, kAzure+4, kOrange+1]
    markers: [kOpenSquare, kOpenCircle, kFullTriangleUp, kFullTriangleUp]
    markersize: 1.
    linewidth: 2
    linestyles: [1,1,1,1]
    fillstyle: [1,1,1,1,0,0,0,0,0,0]
    fillalpha: [0.2,0.2,0.2,0.2,1,1,1,1,1,1]
    drawopt: [histe, histe, hist, hist, e, e, e, e, e]
    
    ratio: 
        enable: true
        uncertainties:
            enable: true
            corr: false
        displayRMS: false

    errcomp: # comparison of uncertainties
        enable: false
        relative: true
    
    KS: false
    dottedLine: ''

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.7, 0.8]
        ylimits: [0.7, 0.9]
        header: 'All'
        titles: ['w/o cut',
                 'with cut',
                ]
        options: [l, l, l, l, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 1

    canvas:
        width: 1600
        heigth: 800
        xaxistitle: 'Cluster size'
        yaxistitle: 'Norm. counts'
        yaxistitleratio: ''
        xlimits: [0., 100.]
        ylimits: [1.e-8, 1.e+2]
        ylimitsratio: [0, 2.5]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
