inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/galucia/PID_ITS/ML_output/V0/no_options/e_score_hist.root,
                /home/galucia/PID_ITS/ML_output/V0/no_options/K_score_hist.root,
                /home/galucia/PID_ITS/ML_output/V0/no_options/p_score_hist.root,
                /home/galucia/PID_ITS/ML_output/V0/no_options/pi_score_hist.root
                ]
    objectnames: ['Test', 'Test', 'Test', 'Test'] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: /home/galucia/PID_ITS/ML_output/V0/beta_pflat/READY_score_hist # with path and w/o extension
    objectnames: ['e', 'K', 'p', 'pi'] # new names for the created objects. Will be AUTOMATICALLY applied if the lenght of the list equals the lenght of the one in the input section
    extensions: [png, root] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1, 1, 1, 1]
    rebin: [1, 1, 1, 1]
    normalize: [true, true, true, true] # divide histogram by its area
    colors: [kCyan, kGreen, kRed, kMagenta]
    markers: [kFullCircle, kFullCircle, kFullCircle, kFullCircle]
    markersize: 1.5
    linewidth: 2
    fillstyle: [0,0,0,0]
    fillalpha: [1,1,1,1]
    drawopt: [hist, hist, hist, hist]
    palette: ['kBlue', 'kBlue', 'kBlue', 'kBlue']
    
    ratio: 
        enable: false
        uncertainties:
            enable: false
            corr: false
        displayRMS: false

    errcomp: # comparison of uncertainties
        enable: false
        relative: true
    
    KS: false
    dottedLine: ''

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.85, 0.95]
        ylimits: [0.75, 0.95]
        header: ''
        titles: [e, K, p, '#pi']
        options: [l, l, l, l]
        textsize: 0.045
        ncolumns: 1

    statlegend:
        x:   0.85
        y:   0.75

    canvas:
        width: 1800
        heigth: 1000
        xaxistitle: '#frac{#Delta}{#beta}'
        yaxistitle: 'Norm. counts'
        yaxistitleratio: ''
        xlimits: [-1, 1]
        ylimits: [0.0001, 1]
        ylimitsratio: [-0.1, 1.5]
        ylimitserr: [0., 0.35]
        logx: false
        logy: True
        logz: true
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false