inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/galucia/PID_ITS/ITS_Cluster_Studies/PID ITS - Giorgio Alberto/code/Check_Hist/BETA_075_078_meanClsize.root,
                /home/galucia/PID_ITS/ITS_Cluster_Studies/PID ITS - Giorgio Alberto/code/Check_Hist/BETA_075_078_meanClsize.root,
                /home/galucia/PID_ITS/ITS_Cluster_Studies/PID ITS - Giorgio Alberto/code/Check_Hist/BETA_075_078_meanClsize.root,
                /home/galucia/PID_ITS/ML_output/TPC/augm_betaflat/Appl_Pi_score_hist.root

                ]
    objectnames: ['2', '1', '0'] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: /home/galucia/PID_ITS/ITS_Cluster_Studies/PID ITS - Giorgio Alberto/code/Check_Hist/BETA_075_078_meanClsize # with path and w/o extension
    objectnames: ['3', '2', '1', 'pi'] # new names for the created objects. Will be AUTOMATICALLY applied if the lenght of the list equals the lenght of the one in the input section
    extensions: [png] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1] # TH1, TH2 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1, 1, 1, 1]
    rebin: [1, 1, 1, 1]
    normalize: [true, true, true, true] # divide histogram by its area
    colors: [kCyan, kGreen, kRed, kMagenta]
    markers: [kFullCircle, kFullCircle, kFullCircle, kFullCircle]
    markersize: 1.5
    linewidth: 2
    fillstyle: [0,0,0,0]
    fillalpha: [1,1,1,1]
    drawopt: [hist, hist, hist, hist]
    palette: ['kBlue', 'kBlue', 'kBlue', 'kBlue']
    
    ratio: 
        enable: false
        uncertainties:
            enable: false
            corr: false
        displayRMS: false

    errcomp: # comparison of uncertainties
        enable: false
        relative: true
    
    KS: true
    dottedLine: ''

    statbox:
        avoid: false
        xlimits: [7, 9]
        ylimits: [0.15, 0.8]
        header: ''
        textsize: 0.03

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.85, 0.95]
        ylimits: [0.55, 0.75]
        header: ''
        titles: ['#pi', K, p]
        options: [l, l, l, l]
        textsize: 0.045
        ncolumns: 1

    statlegend:
        x:   0.85
        y:   0.75

    canvas:
        width: 1800
        heigth: 1000
        xaxistitle: 'meanCLsize'
        yaxistitle: 'Norm. counts'
        yaxistitleratio: ''
        xlimits: [0, 10]
        ylimits: [0.0001, 1.]
        ylimitsratio: [-0.1, 1.5]
        ylimitserr: [0., 0.35]
        logx: false
        logy: true
        logz: true
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false