#
#

TH1:
  settings: { clSizeL0: {title:  "Cl. Size L0; cl. size L0; counts",
                        nBins:  25,
                        xmin:   0,
                        xmax:   25},
              clSizeL1: {title:  "Cl. Size L1; cl. size L1; counts",
                        nBins:  25,
                        xmin:   0,
                        xmax:   25},
              clSizeL2: {title:  "Cl. Size L2; cl. size L2; counts",
                        nBins:  25,
                        xmin:   0,
                        xmax:   25},
              clSizeL3: {title:  "Cl. Size L3; cl. size L3; counts",
                        nBins:  25,
                        xmin:   0,
                        xmax:   25},
              clSizeL4: {title:  "Cl. Size L4; cl. size L4; counts",
                        nBins:  25,
                        xmin:   0,
                        xmax:   25},
              clSizeL5: {title:  "Cl. Size L5; cl. size L5; counts",
                        nBins:  25,
                        xmin:   0,
                        xmax:   25},  
              clSizeL6: {title:  "Cl. Size L6; cl. size L6; counts",
                        nBins:  25,
                        xmin:   0,
                        xmax:   25},
              meanClSize: {title:  "<Cl. Size>; <cl. size>; counts",
                        nBins:  125,
                        xmin:   0,
                        xmax:   25},
              clSizeCosL: {title:  "<Cl. Size> <cos#lambda>; <cl. size> <cos#lambda>; counts",
                        nBins:  250,
                        xmin:   0,
                        xmax:   25},
              p:       {title: "p; p (GeV/c); counts",
                        nBins:  1500,
                        xmin:   0,
                        xmax:   1.5},
              pt:      {title: "p_{T}; p_{T} (GeV/c); counts",
                        nBins:  1500,
                        xmin:   0,
                        xmax:   1.5},
              phi:     {title:  "#phi; #phi; counts",
                        nBins:  100,
                        xmin:   0,
                        xmax:   6.283185307179586},   # 2 pi
              eta:     {title:  "#eta; #eta; counts",
                        nBins:  300,
                        xmin:   -3,
                        xmax:   3},
              tgL:     {title:  "<tan#lambda>; <tan#lambda>; counts",
                        nBins:  80,
                        xmin:   -4,
                        xmax:   4},
              dEdx:    {title:  "dE/dx; dE/dx (); counts",
                        nBins:  100,
                        xmin:   0,
                        xmax:   100},
              nSigmaAbsE: {title:  "|n#sigma_{e}| (); |n#sigma_{e}| (); counts",
                        nBins:  100,
                        xmin:   0,
                        xmax:   10},
              nSigmaAbsPi: {title:  "n#|sigma_{#pi}| (); n#|sigma_{#pi}| (); counts",
                        nBins:  100,
                        xmin:   0,
                        xmax:   10},
              nSigmaAbsK: {title:  "|n#sigma_{K}| (); |n#sigma_{K}| (); counts",
                        nBins:  100,
                        xmin:   0,
                        xmax:   10},
              nSigmaAbsP: {title:  "|n#sigma_{p}| (); |n#sigma_{p}| (); counts",
                        nBins:  100,
                        xmin:   0,
                        xmax:   10}, 
              nSigmaAbsDeu: {title:  "|n#sigma_{d}| (); |n#sigma_{d}| (); counts",
                        nBins:  100,
                        xmin:   0,
                        xmax:   10}, 
            }

TH2:      
  settings: { dEdx_vs_p:  {title:  "dE/dx vs p; p (GeV/c); dE/dx (); counts",
                        x:      "p",
                        nBinsX:  1500,
                        xmin:   0,
                        xmax:   1.5,
                        y:      "dEdx",
                        nBinsY:  100,
                        ymin:   0,
                        ymax:   10000},
              beta_vs_p: {title:  "#beta vs p; p (GeV/c); #beta (); counts",
                        x:     "p",
                        nBinsX:  1500,
                        xmin:   0,
                        xmax:   1.5,
                        y:      "beta",
                        nBinsY:  100,
                        ymin:   0,
                        ymax:   1},
            }