#
#

opt:  'ITS-TPC'

# ali50xl paths
#cfgFile:  {'ITS-TPC': '/home/galucia/ITS_Cluster_Studies/PID_ITS2/configs/cfgPID_ITS-TPC.yml'}
#cfgVisualFile: '/home/galucia/ITS_Cluster_Studies/PID_ITS2/configs/cfgPID_visual.yml'

# local paths
cfgFile:  {'ITS-TPC': '/Users/glucia/Projects/ALICE/ITS_Cluster_Studies/PID_ITS2/configs/cfgPID_ITS-TPC.yml'}
cfgVisualFile: '/Users/glucia/Projects/ALICE/ITS_Cluster_Studies/PID_ITS2/configs/cfgPID_visual.yml'