### INPUT INFO
finPaths:     [/Users/giogi/Desktop/ALICE/ITS_Cluster_Studies/PID_ITS2/output/hybrid/application.root,


              ]
objNames:     ['beta_pred_vs_p',

              ]


### OUTPUT INFO
foutPaths:    [/Users/giogi/Desktop/ALICE/ITS_Cluster_Studies/PID_ITS2/report/img/beta_vs_pHybrid_betaflat,

              ]
outFormats:   [[png],

              ]


### CONFIG  
axisTitles:   [';#it{p} (GeV/#it{c}); #beta',

              ]
axisLimits:   [[0, 0, 1.5, 1],

              ] # [x, ylabel1, ylabel2, ylabel3]
latexLabels:  [[0.6, 0.43, 0.35, 0.27],

              ]
sampleLabels: ['ITS & V0 data - weight in #it{p} and #beta',

              ]
runLabels:    [false,

              ] # true if MC


### CANVAS DIM
canvas:
    width:    [1800,

              ]
    height:   [1000,

              ]