inputs:
    dirname: null # leave null if not common for all input files
    filenames: [/home/fmazzasc/alice/ITS_Cluster_Studies/results/h_proton_clus_520143.root,
    /home/fmazzasc/alice/ITS_Cluster_Studies/results/h_proton_clus_520143.root,
    /home/fmazzasc/alice/ITS_Cluster_Studies/results/h_proton_clus_520143.root,
    /home/fmazzasc/alice/ITS_Cluster_Studies/results/h_proton_clus_520143.root

                ]
    objectnames: [h_proton_clus_slice,
                  h_proton_clus_slice_0,
                  h_proton_clus_slice_1,
                  h_proton_clus_slice_2
                  ] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: bc_cl_size # with path and w/o extension
    extensions: [pdf, png, root] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1, 1., 1, 1., 1., 1., 1., 1.]
    rebin: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    normalize: [false, false, false, false, true, true, true, true, true, true, false, false, false, false] # divide histogram by its area
    normRange: [3, 99]
    colors: [ kBlack, kAzure+4, 
    kRed+1, 
    kOrange+1, 
    ]
    markers: [kOpenSquare, kOpenCircle, kFullTriangleUp, kFullTriangleUp]
    markersize: 1.
    linewidth: 2
    linestyles: [1,1,1,1]
    fillstyle: [0,0,0,0,0,0,0,0,0,0]
    fillalpha: [1,1,1,1,1,1,1,1,1,1]
    drawopt: [hist, hist, hist, hist, hist, e, e, e, e]

    ratio: 
        enable: false
        uncertainties:
            enable: false
            corr: false
        displayRMS: false

    errcomp: # comparison of uncertainties
        enable: false
        relative: true

    KS: false
    dottedLine: ''

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.6, 0.8]
        ylimits: [0.6, 0.9]
        header: '0.4 < p < 0.5 GeV/#it{c}'
        titles: [All,
                 1st BC,
                 2nd BC,
                 3rd BC
                ]
        options: [l, l, l, l, lp, lp, lp, lp, lp]
        textsize: 0.045
        ncolumns: 1

    canvas:
        width: 1300
        heigth: 900
        xaxistitle: '<Cluster Size> x Cos(#lambda)'
        yaxistitle: 'Counts'
        yaxistitleratio: ''
        xlimits: [0.5, 10.5]
        ylimits: [1., 720.]
        ylimitsratio: [0, 1.1]
        ylimitserr: [0., 0.35]
        logy: false
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  